{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "acm-manager.fullname" . }}
  labels:
    control-plane: controller-manager
    {{- include "acm-manager.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
  - Ingress
  ingress:
  - from:
    {{- toYaml .Values.networkPolicy.ingressFrom | nindent 4 }}
    ports:
    - port: 8080
{{- end}}
