/*
Copyright 2021 The acm-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	acmmanagerv1alpha1 "vdesjardins/acm-manager/pkg/apis/acmmanager/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CertificateStatusApplyConfiguration represents a declarative configuration of the CertificateStatus type for use
// with apply.
//
// CertificateStatus defines the observed state of Certificate
type CertificateStatusApplyConfiguration struct {
	// Certificate ARN
	CertificateArn *string `json:"certificateArn,omitempty"`
	// Resource Records for DNS validation
	ResourceRecords []ResourceRecordApplyConfiguration `json:"resourceRecords,omitempty"`
	// Certificate status
	Status *acmmanagerv1alpha1.CertificateStatusType `json:"status,omitempty"`
	// Certificate not before date
	NotBefore *v1.Time `json:"notBefore,omitempty"`
	// Certificate not after date
	NotAfter *v1.Time `json:"notAfter,omitempty"`
}

// CertificateStatusApplyConfiguration constructs a declarative configuration of the CertificateStatus type for use with
// apply.
func CertificateStatus() *CertificateStatusApplyConfiguration {
	return &CertificateStatusApplyConfiguration{}
}

// WithCertificateArn sets the CertificateArn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateArn field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithCertificateArn(value string) *CertificateStatusApplyConfiguration {
	b.CertificateArn = &value
	return b
}

// WithResourceRecords adds the given value to the ResourceRecords field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceRecords field.
func (b *CertificateStatusApplyConfiguration) WithResourceRecords(values ...*ResourceRecordApplyConfiguration) *CertificateStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceRecords")
		}
		b.ResourceRecords = append(b.ResourceRecords, *values[i])
	}
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithStatus(value acmmanagerv1alpha1.CertificateStatusType) *CertificateStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithNotBefore sets the NotBefore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotBefore field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithNotBefore(value v1.Time) *CertificateStatusApplyConfiguration {
	b.NotBefore = &value
	return b
}

// WithNotAfter sets the NotAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotAfter field is set to the value of the last call.
func (b *CertificateStatusApplyConfiguration) WithNotAfter(value v1.Time) *CertificateStatusApplyConfiguration {
	b.NotAfter = &value
	return b
}
