/*
Copyright 2021 The acm-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "vdesjardins/acm-manager/pkg/apis/acmmanager/v1alpha1"
	acmmanagerv1alpha1 "vdesjardins/acm-manager/pkg/client/applyconfiguration/acmmanager/v1alpha1"
	typedacmmanagerv1alpha1 "vdesjardins/acm-manager/pkg/client/versioned/typed/acmmanager/v1alpha1"

	gentype "k8s.io/client-go/gentype"
)

// fakeCertificates implements CertificateInterface
type fakeCertificates struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Certificate, *v1alpha1.CertificateList, *acmmanagerv1alpha1.CertificateApplyConfiguration]
	Fake *FakeAcmmanagerV1alpha1
}

func newFakeCertificates(fake *FakeAcmmanagerV1alpha1, namespace string) typedacmmanagerv1alpha1.CertificateInterface {
	return &fakeCertificates{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Certificate, *v1alpha1.CertificateList, *acmmanagerv1alpha1.CertificateApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("certificates"),
			v1alpha1.SchemeGroupVersion.WithKind("Certificate"),
			func() *v1alpha1.Certificate { return &v1alpha1.Certificate{} },
			func() *v1alpha1.CertificateList { return &v1alpha1.CertificateList{} },
			func(dst, src *v1alpha1.CertificateList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CertificateList) []*v1alpha1.Certificate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CertificateList, items []*v1alpha1.Certificate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
