kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: "kindest/node:v1.31.0"
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
            api-audiences: "kubernetes.svc.default"
            service-account-issuer: "https://S3_BUCKET_NAME_PLACEHOLDER.s3.AWS_REGION_PLACEHOLDER.amazonaws.com/cluster/acm-cluster"
            service-account-jwks-uri: "https://S3_BUCKET_NAME_PLACEHOLDER.s3.AWS_REGION_PLACEHOLDER.amazonaws.com/cluster/acm-cluster/openid/v1/jwks"
            service-account-signing-key-file: "/etc/kubernetes/pki/sa.key"
