/*
Copyright 2021 The acm-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	acmmanagerv1alpha1 "vdesjardins/acm-manager/pkg/apis/acmmanager/v1alpha1"
	applyconfigurationacmmanagerv1alpha1 "vdesjardins/acm-manager/pkg/client/applyconfiguration/acmmanager/v1alpha1"
	scheme "vdesjardins/acm-manager/pkg/client/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CertificatesGetter has a method to return a CertificateInterface.
// A group's client should implement this interface.
type CertificatesGetter interface {
	Certificates(namespace string) CertificateInterface
}

// CertificateInterface has methods to work with Certificate resources.
type CertificateInterface interface {
	Create(ctx context.Context, certificate *acmmanagerv1alpha1.Certificate, opts v1.CreateOptions) (*acmmanagerv1alpha1.Certificate, error)
	Update(ctx context.Context, certificate *acmmanagerv1alpha1.Certificate, opts v1.UpdateOptions) (*acmmanagerv1alpha1.Certificate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, certificate *acmmanagerv1alpha1.Certificate, opts v1.UpdateOptions) (*acmmanagerv1alpha1.Certificate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*acmmanagerv1alpha1.Certificate, error)
	List(ctx context.Context, opts v1.ListOptions) (*acmmanagerv1alpha1.CertificateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *acmmanagerv1alpha1.Certificate, err error)
	Apply(ctx context.Context, certificate *applyconfigurationacmmanagerv1alpha1.CertificateApplyConfiguration, opts v1.ApplyOptions) (result *acmmanagerv1alpha1.Certificate, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, certificate *applyconfigurationacmmanagerv1alpha1.CertificateApplyConfiguration, opts v1.ApplyOptions) (result *acmmanagerv1alpha1.Certificate, err error)
	CertificateExpansion
}

// certificates implements CertificateInterface
type certificates struct {
	*gentype.ClientWithListAndApply[*acmmanagerv1alpha1.Certificate, *acmmanagerv1alpha1.CertificateList, *applyconfigurationacmmanagerv1alpha1.CertificateApplyConfiguration]
}

// newCertificates returns a Certificates
func newCertificates(c *AcmmanagerV1alpha1Client, namespace string) *certificates {
	return &certificates{
		gentype.NewClientWithListAndApply[*acmmanagerv1alpha1.Certificate, *acmmanagerv1alpha1.CertificateList, *applyconfigurationacmmanagerv1alpha1.CertificateApplyConfiguration](
			"certificates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *acmmanagerv1alpha1.Certificate { return &acmmanagerv1alpha1.Certificate{} },
			func() *acmmanagerv1alpha1.CertificateList { return &acmmanagerv1alpha1.CertificateList{} },
		),
	}
}
